### ISSUE TITLE
Green commander do not apeare in the commander selection menu

### ISSUE THREAD

**Issue by Enkre7** [Ferret-Master/Bug-Faction#1]
Hello,
I tried your mod but couldn't test it properly because no green commander appeared in the commander selection menu.
Otherwise great mod keep it up, I find the idea of ​​a biological unit very cool.
If you need a possible French translation i can help you.

**Comment by Ferret-Master** [comment]
A fix has been pushed and it should be live in a few hours

not looking for translations atm but will keep it in mind
